echo "Installing dependencies..."
pip install -r requirements.txt

echo "Running tests..."
# Add test commands here if any

echo "Building Docker image..."
docker login phx.ocir.io -u '<tenancy-namespace>/<username>' -p "$OCIR_PASSWORD"
docker build -t phx.ocir.io/<tenancy-namespace>/simple-python-flask-app:latest .

echo "Pushing Docker image to OCIR..."
docker push phx.ocir.io/<tenancy-namespace>/simple-python-flask-app:latest

echo "Build completed successfully!"
