version: 0.1
component: build
shell: bash

steps:
  - type: Command
    name: Set version
    command: |
      export ARTIFACT_VERSION=$(date -u +%Y%m%d%H%M%S)
      echo $ARTIFACT_VERSION > artifact_version.txt

  - type: Command
    name: Install dependencies
    command: |
      pip install -r requirements.txt

  - type: Command
    name: Run tests
    command: |
      echo "Running tests..."
      # Add test commands here if needed

  - type: Command
    name: Docker login
    command: |
      echo "$PASSWORD_OCIR" | docker login dxb.ocir.io -u "$USERNAME_OCIR" --password-stdin

  - type: Command
    name: Build Docker image
    timeoutInSeconds: 900
    command: |
      export ARTIFACT_VERSION=$(cat artifact_version.txt)
      docker build -t dxb.ocir.io/ax6enss1ld89/demo:$ARTIFACT_VERSION .

  - type: Command
    name: Push Docker image
    timeoutInSeconds: 600
    command: |
      export ARTIFACT_VERSION=$(cat artifact_version.txt)
      docker push dxb.ocir.io/ax6enss1ld89/demo:$ARTIFACT_VERSION

  - type: Command
    name: Generate artifact files
    command: |
      export ARTIFACT_VERSION=$(cat artifact_version.txt)
      echo "dxb.ocir.io/ax6enss1ld89/demo:$ARTIFACT_VERSION" > image.txt

      echo "version: 1.0" > deployment.yaml
      echo "files:" >> deployment.yaml
      echo "  - source: image.txt" >> deployment.yaml
      echo "    destination: /home/opc/image.txt" >> deployment.yaml
      echo "steps:" >> deployment.yaml
      echo "  - run: echo \"Deploying container...\"" >> deployment.yaml
      echo "  - run: docker pull \$(cat /home/opc/image.txt)" >> deployment.yaml
      echo "  - run: docker stop python-flask-app || true" >> deployment.yaml
      echo "  - run: docker rm python-flask-app || true" >> deployment.yaml
      echo "  - run: docker run -d --name python-flask-app -p 5000:5000 \$(cat /home/opc/image.txt)" >> deployment.yaml

outputArtifacts:
  - name: image
    type: BINARY
    location: image.txt

  - name: deployment-config
    type: BINARY
    location: deployment.yaml
