version: 0.1
component: build

shell: bash

steps:
  - type: Command
    name: Install dependencies
    command: |
      pip install -r requirements.txt

  - type: Command
    name: Run tests
    command: |
      echo "Running tests..."
      # Add test commands here if needed

  - type: Command
    name: Docker login
    command: |
      echo "jFF)WKAfyo>8Le8JH(kR" | docker login dxb.ocir.io -u "ax6enss1ld89/imasha.nimantha@onelexiicon.com" --password-stdin

  - type: Command
    name: Build Docker image
    timeoutInSeconds: 900
    command: |
      docker build -t dxb.ocir.io/ax6enss1ld89/demo:latest .

  - type: Command
    name: Push Docker image
    timeoutInSeconds: 900
    command: |
      docker push dxb.ocir.io/ax6enss1ld89/demo:latest

outputArtifacts:
  - name: image
    type: DOCKER_IMAGE
    location: dxb.ocir.io/ax6enss1ld89/demo:latest


