version: 0.1
component: build

shell: bash

vaultVariables:
  OCIR_PASSWORD: ocid1.vaultsecret.oc1.me-dubai-1.amaaaaaaatrw5lyapb7wrgsc6pr7qjcnweyzoaa2boa3o2ih53uocwzblk5q
  OCIR_USERNAME: ocid1.vaultsecret.oc1.me-dubai-1.amaaaaaaatrw5lyakak3l45lqfxawh24j7fsj5l54ch7dq7dpr4hotji4nva

steps:
  - type: Command
    name: Install dependencies
    command: |
      pip install -r requirements.txt

  - type: Command
    name: Run tests
    command: |
      echo "Running tests..."
      # Add test commands here if needed

  - type: Command
    name: Docker login
    command: |
      echo "$OCIR_PASSWORD" | docker login dxb.ocir.io -u "$OCIR_USERNAME" --password-stdin

  - type: Command
    name: Build Docker image
    command: |
      docker build -t dxb.ocir.io/ax6enss1ld89/simple-python-flask-app:latest .

  - type: Command
    name: Push Docker image
    command: |
      docker push dxb.ocir.io/ax6enss1ld89/simple-python-flask-app:latest

outputArtifacts:
  - name: image
    type: DOCKER_IMAGE
    location: dxb.ocir.io/ax6enss1ld89/simple-python-flask-app:latest
